### PR TITLE
F-Sol for hard

### PR DESCRIPTION
**Pull request by OnFireTurki**
This should solve the problem. I find out that there was an error with passing columns-rows parameters.

### CODE REVIEW

**Comment by mohalobaidi** [comment]
For 5, 26, "A1", "B2", "A2"
Output: ["A1", "E5", "B2"]
Expected: ["A1", B2"]

**Comment by OnFireTurki** [comment]
> For 5, 26, "A1", "B2", "A2" Output: ["A1", "E5", "B2"] Expected: ["A1", B2"]

Fixed, I have removed the easy level basic solution which was the cause of this issue.
I hope you can review my solution again, and I'm sorry for the "too many attempts"

**Comment by mohalobaidi** [comment]
For 5, 26, "A1", "A1", "A2"
Output: [NON]
Expected: ["A1"]

One final tweak  😇

**Comment by OnFireTurki** [comment]
Done

**Pull request closed without merging**
